# -*- coding: utf-8 -*-
"""Lyra_botrytis_7B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xwfZZfUi2ukX_0Lq4asWDgD0rRsnONoX
"""

# Bloc 1 — Install & vérification des fichiers JSONL
!pip install -q --upgrade "transformers>=4.46.0" peft datasets trl accelerate huggingface_hub

import transformers
import trl
import torch

print("transformers version :", transformers.__version__)
print("trl version          :", trl.__version__)
print("torch version        :", torch.__version__)
print("CUDA dispo:", torch.cuda.is_available())

import os, json

# 🔧 chemins vers les datasets
train_path = "/content/sample_data/dataset_mildiou_1500_train.jsonl"
valid_path = "/content/sample_data/dataset_mildiou_validation_149.jsonl"  # petit jeu d'éval manuel

def check_jsonl(path, n=3):
    print(f"\n🔍 Vérification du fichier : {path}")
    if not os.path.exists(path):
        print("❌ Fichier introuvable.")
        return False
    try:
        with open(path, "r", encoding="utf-8") as f:
            lines = [next(f).strip() for _ in range(n)]
        print(f"✅ Fichier trouvé ({os.path.getsize(path)/1024:.1f} Ko)")
        for i, line in enumerate(lines, 1):
            data = json.loads(line)
            print(f"— Ligne {i} OK, clés principales :", list(data.keys()))
        print("✅ Structure JSONL valide (au moins sur les 3 premières lignes).")
        return True
    except Exception as e:
        print("⚠️ Erreur :", e)
        return False

ok_train = check_jsonl(train_path)
ok_valid = check_jsonl(valid_path)

if ok_train and ok_valid:
    print("\n🚀 Les deux datasets sont valides et prêts à être chargés.")
else:
    print("\n⚠️ Problème détecté sur au moins un des fichiers.")

# Bloc 2 — Login Hugging Face avec TOKEN_HF_Mildew
import torch, os
from google.colab import userdata
from huggingface_hub import login

base_model_id = "mistralai/Mistral-7B-Instruct-v0.3"

print("GPU :", torch.cuda.get_device_name(0))
print("CUDA dispo:", torch.cuda.is_available())

# 🔐 secret Colab doit s'appeler TOKEN_HF_Mildew
hf_token = userdata.get('TOKEN_HF_Mildew')
if not hf_token:
    raise ValueError("❌ Le secret TOKEN_HF_Botrytis est introuvable ou vide.")
os.environ["HF_TOKEN"] = hf_token

login(token=os.environ["HF_TOKEN"])
print("🔐 Connexion Hugging Face OK")

# Bloc 3 — Chargement du JSONL & application chat template avec prompt système

import json
from datasets import Dataset, DatasetDict
from transformers import AutoTokenizer

def load_jsonl(path):
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows

train_rows = load_jsonl(train_path)
valid_rows = load_jsonl(valid_path)

dataset = DatasetDict({
    "train": Dataset.from_list(train_rows),
    "validation": Dataset.from_list(valid_rows)
})

print("taille train :", len(dataset["train"]))
print("taille valid :", len(dataset["validation"]))
print("exemple brut :", dataset["train"][0])

tokenizer = AutoTokenizer.from_pretrained(base_model_id, use_fast=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

SYSTEM_PROMPT = """Tu es un agronome spécialisé dans les maladies fongiques de la vigne, en particulier le mildiou (Plasmopara viticola).
Ton rôle est d’évaluer le risque d’infection à partir d’un ensemble réduit de variables, puis de formuler une recommandation agronomique courte, claire et actionnable.

Les variables fournies dans les requêtes sont :
- Stade_phenologique (texte) : "jeunes_feuilles", "floraison", ou "autre" (stade moins sensible).
- Humectation_continue (heures) : durée ininterrompue de mouillage foliaire (pluie ou rosée) au cours des 24 dernières heures. Une valeur ≥6h en conditions favorables (16–22°C) indique un risque d’infection.
- Temperature_moyenne (°C) : température moyenne sur les dernières 24h. La zone 16–22°C est optimale pour l’infection.
- Pluie_24h (mm) : cumul de pluie sur les dernières 24h. ≥10 mm déclenche la libération de zoospores.
- Inoculum (0 à 1) : pression d’inoculum, basée sur le nombre d’années infectées sur les 3 dernières années (0.3 = faible, 0.5 = modéré, 0.7 = élevé, 0.9 = très élevé).

Ta réponse doit toujours comporter exactement deux éléments :
1) Un niveau de risque parmi : « faible », « moyen », ou « élevé ».
2) Une recommandation agronomique opérationnelle, simple et concise (1 à 3 phrases maximum), adaptée au risque et aux pratiques viticoles.

Règles strictes :
- Ne jamais mentionner d’autres facteurs ou produire des informations non demandées.
- Respecter strictement le format :
  Risque : [faible/moyen/élevé]
  Recommandation : [texte concis et pragmatique]

Priorités pour l’évaluation :
- La floraison (BBCH 61–69) et les jeunes feuilles (BBCH 12–17) sont des stades critiques (majoration automatique du risque).
- Une humectation ≥6h + température 16–22°C + pluie ≥10mm = conditions idéales pour une infection explosive.
- Les recommandations doivent être directement applicables (ex : "Traiter avec du cuivre sous 24h" ou "Surveillance renforcée").
- Ne pas inclure de détails superflus ou de justifications.

Exemple de sortie :
Risque : élevé
Recommandation : Appliquer un traitement à base de cuivre ou un fongicide systémique autorisé sous 24h, en ciblant les inflorescences et jeunes feuilles. Renouveler après une nouvelle pluie.
"""

def to_chat_text(example):
    # On suppose que example["messages"] contient déjà user + assistant,
    # sans message système. On le préfixe par le SYSTEM_PROMPT.
    chat_messages = [{"role": "system", "content": SYSTEM_PROMPT}] + example["messages"]
    txt = tokenizer.apply_chat_template(
        chat_messages,
        tokenize=False,
        add_generation_prompt=False,
    )
    return {"text": txt}

dataset = dataset.map(to_chat_text)

print("aperçu text :", dataset["train"][0]["text"][:500])

print("transformers version :", transformers.__version__)
print("trl version          :", trl.__version__)
print("torch version        :", torch.__version__)
print("CUDA dispo:", torch.cuda.is_available())

# Bloc 4 — Chargement du modèle de base & configuration LoRA

from transformers import AutoModelForCausalLM
from peft import LoraConfig, get_peft_model
import torch

base_model_id = "mistralai/Mistral-7B-Instruct-v0.3"

model = AutoModelForCausalLM.from_pretrained(
    base_model_id,
    torch_dtype=torch.float16,
    device_map="auto",   # accelerate répartit sur le GPU (et CPU si besoin)
)

lora_config = LoraConfig(
    r=64,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    ],
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# Bloc 5 — SFTTrainer + hyperparamètres Mildew
from trl import SFTTrainer
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./lyra_Mildew_LoRA",   # dossier de travail (checkpoints intermédiaires)
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,
    fp16=True,
    logging_steps=10,
    eval_strategy="epoch",
    save_strategy="epoch",
    lr_scheduler_type="cosine",
    warmup_ratio=0.03,
    weight_decay=0.0,
    report_to="none",
)

trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=dataset["train"],
    eval_dataset=dataset["validation"],
    args=training_args,
)

trainer.train()

# Bloc 6 — Sauvegarde des adapters dans ./lyra_Mildew_adapter

output_dir = "./lyra_Mildew_adapter"

trainer.model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)

print("Adapters sauvegardés dans", output_dir)
!ls -R {output_dir}

### 📤 Bloc 7 — Push du modèle sur Hugging Face


from huggingface_hub import create_repo

# ⬇️ username HF
hf_repo_id = "jeromex1/lyra_Mildew_mistral7B_LoRA"

print("Repo cible :", hf_repo_id)

# Crée le repo si besoin
create_repo(hf_repo_id, exist_ok=True)

# Push du modèle (adapters PEFT) et du tokenizer
trainer.model.push_to_hub(hf_repo_id)
tokenizer.push_to_hub(hf_repo_id)

print(f"✅ Modèle et tokenizer poussés sur : https://huggingface.co/{hf_repo_id}")

# Bloc 8 — Inférences de test sur quelques situations Mildiou
import torch
model.eval()

# Prompt système pour le mildiou (à définir en haut de ton script)
SYSTEM_PROMPT = """
Tu es un agronome spécialisé dans le mildiou de la vigne (Plasmopara viticola).
Ton rôle est d'évaluer le risque d'infection à partir des paramètres suivants, puis de formuler une recommandation agronomique concise.

Format attendu :
Risque : [faible/moyen/élevé]
Recommandation : [1-3 phrases max, actionnable et spécifique]
"""

def format_user(stade, humectation, temperature, pluie, inoculum):
    return (
        f"Stade_phenologique: {stade}\n"
        f"Humectation_continue: {humectation}\n"
        f"Temperature_moyenne: {temperature}\n"
        f"Pluie_24h: {pluie}\n"
        f"Inoculum: {inoculum}\n\n"
        "Évalue le risque de mildiou et propose une recommandation agronomique."
    )

def infer_case(stade, humectation, temperature, pluie, inoculum, label=""):
    user_content = format_user(stade, humectation, temperature, pluie, inoculum)
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )
    inputs = tokenizer(text, return_tensors="pt").to(model.device)
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=200,
            do_sample=False,  # Sortie stable et reproductible
        )
    # Décodage de la réponse (sans le prompt)
    generated = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True,
    ).strip()
    print("=" * 80)
    if label:
        print(f"🧪 Cas de test : {label}")
    print("Input :")
    print(user_content)
    print("\nRéponse du modèle :")
    print(generated)
    print()

# --- Cas de test : Risque FAIBLE ---
# Cas 1 : Conditions défavorables (température élevée, pas de pluie)
infer_case(
    stade="autre",
    humectation=3,
    temperature=25,
    pluie=0,
    inoculum=0.2,
    label="Faible 1 — Température trop élevée, pas de pluie, inoculum faible",
)

# Cas 2 : Humectation insuffisante
infer_case(
    stade="jeunes_feuilles",
    humectation=4,
    temperature=18,
    pluie=2,
    inoculum=0.3,
    label="Faible 2 — Humectation <6h, pluie faible, stade peu sensible",
)

# Cas 3 : Stade non critique + conditions limites
infer_case(
    stade="autre",
    humectation=5,
    temperature=15,
    pluie=1,
    inoculum=0.1,
    label="Faible 3 — Température sous-optimale, humectation courte",
)

# Cas 4 : Inoculum très faible malgré humectation modérée
infer_case(
    stade="autre",
    humectation=6,
    temperature=20,
    pluie=0,
    inoculum=0.1,
    label="Faible 4 — Humectation seuil mais pluie absente et inoculum très faible",
)

# --- Cas de test : Risque MOYEN ---
# Cas 5 : Jeunes feuilles + humectation modérée
infer_case(
    stade="jeunes_feuilles",
    humectation=7,
    temperature=19,
    pluie=5,
    inoculum=0.5,
    label="Moyen 1 — Jeunes feuilles sensibles, humectation proche du seuil",
)

# Cas 6 : Floraison mais conditions limites
infer_case(
    stade="floraison",
    humectation=6,
    temperature=17,
    pluie=4,
    inoculum=0.4,
    label="Moyen 2 — Floraison mais humectation/pluie limites",
)

# Cas 7 : Humectation longue mais température sous-optimale
infer_case(
    stade="jeunes_feuilles",
    humectation=9,
    temperature=15,
    pluie=6,
    inoculum=0.6,
    label="Moyen 3 — Humectation prolongée mais température fraîche",
)

# Cas 8 : Pluie modérée + inoculum intermédiaire
infer_case(
    stade="autre",
    humectation=8,
    temperature=20,
    pluie=7,
    inoculum=0.5,
    label="Moyen 4 — Pluie modérée, inoculum moyen, stade non critique",
)

# --- Cas de test : Risque ÉLEVÉ ---
# Cas 9 : Floraison + conditions optimales
infer_case(
    stade="floraison",
    humectation=12,
    temperature=20,
    pluie=10,
    inoculum=0.7,
    label="Élevé 1 — Floraison + humectation/pluie/température optimales",
)

# Cas 10 : Jeunes feuilles + inoculum élevé
infer_case(
    stade="jeunes_feuilles",
    humectation=14,
    temperature=19,
    pluie=12,
    inoculum=0.8,
    label="Élevé 2 — Jeunes feuilles, forte pression d'inoculum, conditions idéales",
)

# Cas 11 : Humectation extrême + pluie abondante
infer_case(
    stade="floraison",
    humectation=18,
    temperature=21,
    pluie=15,
    inoculum=0.6,
    label="Élevé 3 — Humectation très longue + pluie abondante en floraison",
)

# Cas 12 : Tous les facteurs défavorables
infer_case(
    stade="floraison",
    humectation=20,
    temperature=22,
    pluie=20,
    inoculum=0.9,
    label="Élevé 4 — Tous les feux au rouge (floraison, conditions extrêmes)",
)

#########################################
# entrainement complémentaire si besoin #
#########################################

# Bloc MD2 — Run de correction 1 epoch sur le mini-dataset "high risk zone"

from datasets import Dataset
from transformers import TrainingArguments
from trl import SFTTrainer

# 1) Chargement du mini-dataset JSONL

middle_path = "/content/sample_data/Mildew_dataset_middle_30.jsonl"

def load_jsonl(path):
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows

middle_rows = load_jsonl(middle_path)
middle_dataset = Dataset.from_list(middle_rows)

print("Taille mini-dataset middle zone :", len(middle_dataset))

# 2) Conversion en texte avec le même chat template que le reste
middle_dataset = middle_dataset.map(to_chat_text)
print("Exemple text middle :", middle_dataset[0]["text"][:400])

# 3) Nouveaux TrainingArguments pour une micro-correction
correction_args = TrainingArguments(
    output_dir="./lyra_Mildew_LoRA_middle_fix",
    num_train_epochs=1,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    learning_rate=1e-4,          # un peu plus doux pour une correction fine
    fp16=True,
    logging_steps=1,
    save_strategy="no",          # pas besoin de checkpoints multiples
    report_to="none",
)

correction_trainer = SFTTrainer(
    model=model,                     # modèle LoRA déjà entraîné
    processing_class=tokenizer,
    train_dataset=middle_dataset,
    args=correction_args,
)

correction_trainer.train()

# 4) Sauvegarde des adapters corrigés dans un nouveau dossier
output_dir_fix = "./lyra_Mildew_adapter_middle_fix"
correction_trainer.model.save_pretrained(output_dir_fix)
tokenizer.save_pretrained(output_dir_fix)

print("✅ Adapters corrigés sauvegardés dans :", output_dir_fix)
!ls -R {output_dir_fix}

# remplacement des adapters
from huggingface_hub import HfApi, upload_folder

hf_repo_id = "jeromex1/lyra_Mildew_mistral7B_LoRA"
adapter_dir_fix = "./lyra_Mildew_adapter_middle_fix"

api = HfApi()

upload_folder(
    repo_id=hf_repo_id,
    folder_path=adapter_dir_fix,
    commit_message="Update with middle-zone calibrated LoRA adapters",
)
print("✅ Adapters corrigés poussés sur Hugging Face :", hf_repo_id)